[project]
authors = ["Shlok Natarajan <shlok.natarajan@gmail.com>"]
channels = ["conda-forge"]
name = "autogkb-prompt-tester"
platforms = ["osx-arm64"]
version = "0.1.0"


[dependencies]
python = ">=3.13.7,<3.14"
pydantic = ">=2.11.9,<3"
python-dotenv = ">=1.1.1,<2"
fastapi = ">=0.118.0,<0.119"
uvicorn = ">=0.38.0,<0.39"
openai = ">=2.2.0,<3"
numpy = ">=2.3.4,<3"
sentence-transformers = ">=5.1.2,<6"
loguru = ">=0.7.3,<0.8"

[tasks]
# Backend tasks
be = "uvicorn main:app --reload"
backend = { depends-on = ["be"] }

# Frontend tasks
fe = { cmd = "npm run dev", cwd = "frontend" }
frontend = { depends-on = ["fe"] }

# Run both frontend and backend concurrently
dev = { depends-on = ["be", "fe"] }
start = { depends-on = ["dev"] }
